filter:
    paths: [app/*]
    excluded_paths: [bootstrap/*, config/*, database/*, public/*, resource/*, vendor/*]

checks:
    php:
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

tools:
    external_code_coverage:
        timeout: 1200
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["app/*", "tests/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["app/*", "tests/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml.dist
            design_rules: { eval_expression: false }
        filter:
            paths: ["app/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "examples", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["app/*", "tests/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["app/*", "tests/*"]
    sensiolabs_security_checker: true
